There is no Scheduler.parallel
```
File "handson_activity/act02_gensym_atomics/gensym_atomics.ml", line 36, characters 15-33:
36 |   let result = Scheduler.parallel scheduler ~f in
                    ^^^^^^^^^^^^^^^^^^
Error: Unbound value Scheduler.parallel
```

Use Scheduler.schedule instead (also requires creating a Monitor)

Signed-off-by: Edwin Török <edwin@etorok.net>